[0;33m--- idf_monitor on /dev/ttyUSB0 115200 ---[0m
[0;33m--- Quit: Ctrl+] | Menu: Ctrl+T | Help: Ctrl+T followed by Ctrl+H ---[0m
[0;33mStack dump detected[0m
[0;33m0x40389596: vPortClearInterruptMask at /home/rome/esp/esp-idf/components/freertos/FreeRTOS-Kernel/portable/riscv/port.c:385
[0m
[0;33m0x403895c0: vPortExitCritical at /home/rome/esp/esp-idf/components/freertos/FreeRTOS-Kernel/portable/riscv/port.c:339
[0m
[0;33m0x42054c72: ieee80211_timer_process at ??:?
[0m
[0;33m0x4038916e: ulTaskGenericNotifyTake at /home/rome/esp/esp-idf/components/freertos/FreeRTOS-Kernel/tasks.c:5822
[0m
[0;33m0x40389596: vPortClearInterruptMask at /home/rome/esp/esp-idf/components/freertos/FreeRTOS-Kernel/portable/riscv/port.c:385
[0m
[0;33m0x403895c0: vPortExitCritical at /home/rome/esp/esp-idf/components/freertos/FreeRTOS-Kernel/portable/riscv/port.c:339
[0m
[0;33m0x42054c72: ieee80211_timer_process at ??:?
[0m
[0;33m0x4038916e: ulTaskGenericNotifyTake at /home/rome/esp/esp-idf/components/freertos/FreeRTOS-Kernel/tasks.c:5822
[0m
[0;33m0x40389596: vPortClearInterruptMask at /home/rome/esp/esp-idf/components/freertos/FreeRTOS-Kernel/portable/riscv/port.c:385
[0m
[0;33m0x403895c0: vPortExitCritical at /home/rome/esp/esp-idf/components/freertos/FreeRTOS-Kernel/portable/riscv/port.c:339
[0m
[0;33m0x42054c72: ieee80211_timer_process at ??:?
[0m
[0;33m0x4038916e: ulTaskGenericNotifyTake at /home/rome/esp/esp-idf/components/freertos/FreeRTOS-Kernel/tasks.c:5822
[0m
[0;33m0x40389596: vPortClearInterruptMask at /home/rome/esp/esp-idf/components/freertos/FreeRTOS-Kernel/portable/riscv/port.c:385
[0m
[0;33m0x403895c0: vPortExitCritical at /home/rome/esp/esp-idf/components/freertos/FreeRTOS-Kernel/portable/riscv/port.c:339
[0m
[0;33m0x42054c72: ieee80211_timer_process at ??:?
[0m
[0;33m0x4038916e: ulTaskGenericNotifyTake at /home/rome/esp/esp-idf/components/freertos/FreeRTOS-Kernel/tasks.c:5822
[0m
[0;33m0x40389596: vPortClearInterruptMask at /home/rome/esp/esp-idf/components/freertos/FreeRTOS-Kernel/portable/riscv/port.c:385
[0m
[0;33m0x403895c0: vPortExitCritical at /home/rome/esp/esp-idf/components/freertos/FreeRTOS-Kernel/portable/riscv/port.c:339
[0m
[0;33m0x42054c72: ieee80211_timer_process at ??:?
[0m
[0;33m0x4038916e: ulTaskGenericNotifyTake at /home/rome/esp/esp-idf/components/freertos/FreeRTOS-Kernel/tasks.c:5822
[0m
[0;33mFailed to run gdb_panic_server.py script: Command '['riscv32-esp-elf-gdb', '--batch', '-n', '/home/rome/esp/esp_workspace/esp_workspace/tcp/build/mqtt_tcp.elf', '-ex', 'target remote | "/home/rome/.espressif/python_env/idf5.1_py3.10_env/bin/python" "/home/rome/.espressif/python_env/idf5.1_py3.10_env/lib/python3.10/site-packages/esp_idf_monitor/base/../gdb_panic_server.py" --target esp32c3 "/tmp/tmp0kg951h2"', '-ex', 'bt']' returned non-zero exit status 1.
b'Traceback (most recent call last):\n  File "/home/rome/.espressif/python_env/idf5.1_py3.10_env/lib/python3.10/site-packages/esp_idf_monitor/base/../gdb_panic_server.py", line 291, in <module>\n    main()\n  File "/home/rome/.espressif/python_env/idf5.1_py3.10_env/lib/python3.10/site-packages/esp_idf_monitor/base/../gdb_panic_server.py", line 281, in main\n    panic_info = PANIC_OUTPUT_PARSERS[args.target](args.input_file.read())\n  File "/home/rome/.espressif/python_env/idf5.1_py3.10_env/lib/python3.10/site-packages/esp_idf_monitor/base/../gdb_panic_server.py", line 134, in parse_idf_riscv_panic_output\n    raise ValueError("Couldn\'t parse panic handler output")\nValueError: Couldn\'t parse panic handler output\nRemote communication error.  Target disconnected.: Conexi\xc3\xb3n reinicializada por la m\xc3\xa1quina remota.\nNo stack.\n'

[0m
[0;33mStack dump detected[0m
[0;33m0x40389596: vPortClearInterruptMask at /home/rome/esp/esp-idf/components/freertos/FreeRTOS-Kernel/portable/riscv/port.c:385
[0m
[0;33m0x403895c0: vPortExitCritical at /home/rome/esp/esp-idf/components/freertos/FreeRTOS-Kernel/portable/riscv/port.c:339
[0m
[0;33m0x42054c72: ieee80211_timer_process at ??:?
[0m
[0;33m0x4038916e: ulTaskGenericNotifyTake at /home/rome/esp/esp-idf/components/freertos/FreeRTOS-Kernel/tasks.c:5822
[0m
[0;33m0x40389596: vPortClearInterruptMask at /home/rome/esp/esp-idf/components/freertos/FreeRTOS-Kernel/portable/riscv/port.c:385
[0m
[0;33m0x403895c0: vPortExitCritical at /home/rome/esp/esp-idf/components/freertos/FreeRTOS-Kernel/portable/riscv/port.c:339
[0m
[0;33m0x42054c72: ieee80211_timer_process at ??:?
[0m
[0;33m0x4038916e: ulTaskGenericNotifyTake at /home/rome/esp/esp-idf/components/freertos/FreeRTOS-Kernel/tasks.c:5822
[0m
[0;33m0x40389596: vPortClearInterruptMask at /home/rome/esp/esp-idf/components/freertos/FreeRTOS-Kernel/portable/riscv/port.c:385
[0m
[0;33m0x403895c0: vPortExitCritical at /home/rome/esp/esp-idf/components/freertos/FreeRTOS-Kernel/portable/riscv/port.c:339
[0m
[0;33m0x42054c72: ieee80211_timer_process at ??:?
[0m
[0;33m0x4038916e: ulTaskGenericNotifyTake at /home/rome/esp/esp-idf/components/freertos/FreeRTOS-Kernel/tasks.c:5822
[0m
[0;33m0x40389596: vPortClearInterruptMask at /home/rome/esp/esp-idf/components/freertos/FreeRTOS-Kernel/portable/riscv/port.c:385
[0m
[0;33m0x403895c0: vPortExitCritical at /home/rome/esp/esp-idf/components/freertos/FreeRTOS-Kernel/portable/riscv/port.c:339
[0m
[0;33m0x42054c72: ieee80211_timer_process at ??:?
[0m
[0;33m0x4038916e: ulTaskGenericNotifyTake at /home/rome/esp/esp-idf/components/freertos/FreeRTOS-Kernel/tasks.c:5822
[0m
[0;33m0x40389596: vPortClearInterruptMask at /home/rome/esp/esp-idf/components/freertos/FreeRTOS-Kernel/portable/riscv/port.c:385
[0m
[0;33m0x403895c0: vPortExitCritical at /home/rome/esp/esp-idf/components/freertos/FreeRTOS-Kernel/portable/riscv/port.c:339
[0m
[0;33m0x42054c72: ieee80211_timer_process at ??:?
[0m
[0;33m0x4038916e: ulTaskGenericNotifyTake at /home/rome/esp/esp-idf/components/freertos/FreeRTOS-Kernel/tasks.c:5822
[0m
[0;33m0x40389596: vPortClearInterruptMask at /home/rome/esp/esp-idf/components/freertos/FreeRTOS-Kernel/portable/riscv/port.c:385
[0m
[0;33m0x403895c0: vPortExitCritical at /home/rome/esp/esp-idf/components/freertos/FreeRTOS-Kernel/portable/riscv/port.c:339
[0m
[0;33m0x42054c72: ieee80211_timer_process at ??:?
[0m
[0;33m0x4038916e: ulTaskGenericNotifyTake at /home/rome/esp/esp-idf/components/freertos/FreeRTOS-Kernel/tasks.c:5822
[0m
[0;33m0x40389596: vPortClearInterruptMask at /home/rome/esp/esp-idf/components/freertos/FreeRTOS-Kernel/portable/riscv/port.c:385
[0m
[0;33m0x403895c0: vPortExitCritical at /home/rome/esp/esp-idf/components/freertos/FreeRTOS-Kernel/portable/riscv/port.c:339
[0m
[0;33m0x42054c72: ieee80211_timer_process at ??:?
[0m
[0;33m0x4038916e: ulTaskGenericNotifyTake at /home/rome/esp/esp-idf/components/freertos/FreeRTOS-Kernel/tasks.c:5822
[0m
[0;33m0x40389596: vPortClearInterruptMask at /home/rome/esp/esp-idf/components/freertos/FreeRTOS-Kernel/portable/riscv/port.c:385
[0m
[0;33m0x403895c0: vPortExitCritical at /home/rome/esp/esp-idf/components/freertos/FreeRTOS-Kernel/portable/riscv/port.c:339
[0m
[0;33m0x42054c72: ieee80211_timer_process at ??:?
[0m
[0;33m0x4038916e: ulTaskGenericNotifyTake at /home/rome/esp/esp-idf/components/freertos/FreeRTOS-Kernel/tasks.c:5822
[0m
Exception in thread Thread-2 (_run_outer):
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/home/rome/.espressif/python_env/idf5.1_py3.10_env/lib/python3.10/site-packages/esp_idf_monitor/base/stoppable_thread.py", line 47, in _run_outer
    self.run()
  File "/home/rome/.espressif/python_env/idf5.1_py3.10_env/lib/python3.10/site-packages/esp_idf_monitor/base/serial_reader.py", line 100, in run
    self.close_serial()
  File "/home/rome/.espressif/python_env/idf5.1_py3.10_env/lib/python3.10/site-packages/esp_idf_monitor/base/serial_reader.py", line 105, in close_serial
    self.set_closing_wait(delay_sec=1)
  File "/home/rome/.espressif/python_env/idf5.1_py3.10_env/lib/python3.10/site-packages/esp_idf_monitor/base/serial_reader.py", line 128, in set_closing_wait
    fcntl.ioctl(self.serial.fd, termios.TIOCSSERIAL, buf)
PermissionError: [Errno 1] Operation not permitted
[0m
